### ISSUE TITLE
Class Shortcut

### ISSUE THREAD

**Issue by pdrey919** [Digitalbrainstem/ejs-grammar#37] opened 2019-07-31 18:36 UTC
Hey There, first off thanks for this great extension. I'm just getting started with VSCode and this is already a game-changer for writing ejs. 
There is one thing that's nagging me, though. In Sublime Text html files (and VSCode as well), you can create a set of html tags and assign them a class by writing `h1.hello`  and hitting tab, which would turn it into `<h1 class="hello"></h1>`

Is this something you could add in future? Thanks.

**Comment by ExE-Boss** [comment] 2019-07-31 19:31
Duplicate of #10

**Closed by ExE-Boss** 2019-07-31 19:31 UTC
